version: "3.8"

services:
  daereview:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-https://daereview.daeroom.my.id}
        NEXT_PUBLIC_GSC_VERIFICATION: ${NEXT_PUBLIC_GSC_VERIFICATION:-_5BNDxoJkGkVL-YfDLstufxHtU9pfpI_YYVncEmX6H4}
    container_name: daereview
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - ADMIN_SECRET_KEY=${ADMIN_SECRET_KEY}
      - ADMIN_SALT_SECRET=${ADMIN_SALT_SECRET}
      - DIFY_WEBHOOK_SECRET=${DIFY_WEBHOOK_SECRET}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-https://daereview.daeroom.my.id}
      - NEXT_PUBLIC_GSC_VERIFICATION=${NEXT_PUBLIC_GSC_VERIFICATION:-_5BNDxoJkGkVL-YfDLstufxHtU9pfpI_YYVncEmX6H4}
    volumes:
      - daereview_data:/app/src/data

volumes:
  daereview_data:
    driver: local
